ARG BASE_IMAGE=nvblox_deps
ARG CMAKE_ARGS=""

FROM $BASE_IMAGE

SHELL ["/bin/bash", "-c"]

# Copy over nvblox
COPY . nvblox

# Build the standalone library
RUN cd nvblox/nvblox && mkdir build && cd build && \
    cmake .. $CMAKE_ARGS && make -j8

RUN cd nvblox && pip install --editable python/evaluation python/scripts python/common
