# Use a lightweight Python image
FROM python:3.12.3-slim

# Set the working directory
WORKDIR /nvblox

# Install system packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    doxygen \
    && rm -rf /var/lib/apt/lists/*

# Install python deps
COPY docs/requirements.txt /
RUN pip install --no-cache-dir --upgrade pip \
    && pip3 install --no-cache-dir -r /requirements.txt

# Set the entrypoint to bash
ENTRYPOINT ["bash"]
