ARG BASE_IMAGE=nvblox_deps

FROM $BASE_IMAGE
ARG CMAKE_ARGS=""
ARG MAX_NUM_JOBS=20

SHELL ["/bin/bash", "-c"]

# First we only copy files needed for the cpp build. This is to avoid re-triggering the build when
# irrelevant files are modified.
# NOTE(dtingdahl) This can be reduced to a single COPY --parents command once syntax version 1.7-labs is
# supported.
RUN mkdir -p /nvblox/nvblox_torch/cpp /nvblox/cmake /nvblox/nvblox_renderer
COPY CMakeLists.txt /nvblox/
COPY cmake /nvblox/cmake
COPY nvblox /nvblox/nvblox
COPY nvblox_torch/cpp /nvblox/nvblox_torch/cpp/
COPY nvblox_renderer /nvblox/nvblox_renderer
COPY executables /nvblox/executables

# Build the standalone library. Note that 'bash -i' is needed to pickup the custom CMAKE_PREFIX_PATH
# defined in bashrc
RUN cd nvblox && mkdir build && cd build && \
    # To avoid out-of-memory, we limit the number of build jobs to max(num_cpu_cores, MAX_NUM_JOBS).
    NUM_JOBS=$(echo "$(nproc) $MAX_NUM_JOBS" | awk '{print ($1<$2)?$1:$2}') && \
    echo "Number of build jobs: $NUM_JOBS" && \
    bash -ic "cmake ..  ${CMAKE_ARGS} && make -j $NUM_JOBS"

# Copy the complete source tree and install nvblox_torch if supported on the current platform.
# Note that we need to copy the full repo, including the .git dir, to read the current commit-SHA.
COPY . /nvblox
RUN python3 /nvblox/docker/torch_install_helper.py --install-nvblox-torch-if-supported
