name: 'Checkout Code'
description: 'Wipe workspace and checkout code with LFS support'
runs:
  using: 'composite'
  steps:
    - name: Wipe workspace
      shell: bash
      run: |
        rm -rf ./* || true
        rm -rf ./.??* || true
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        lfs: true
