name: 'Build and Test'
description: 'Build nvblox Docker image and run tests'
inputs:
  platform:
    description: 'Platform to build for'
    required: true
  cuda-version:
    description: 'CUDA version'
    required: true
  ubuntu-version:
    description: 'Ubuntu version'
    required: true
  ngc-api-key:
    description: 'NGC API Key for authentication'
    required: true
runs:
  using: 'composite'
  steps:
    - name: NGC Login
      uses: ./.github/actions/ngc-login
      with:
        ngc-api-key: ${{ inputs.ngc-api-key }}
    - name: Run CPP unit tests
      shell: bash
      run: |
        echo "::group::Run CPP unit tests"
        ci/premerge.py  --platform ${{ inputs.platform }} \
                        --cuda-version ${{ inputs.cuda-version }} \
                        --ubuntu-version ${{ inputs.ubuntu-version }} \
                        --build-and-test cpp
        echo "::endgroup::"
    - name: Run Python unit tests
      shell: bash
      run: |
        echo "::group::Run Python unit tests"
        ci/premerge.py  --platform ${{ inputs.platform }} \
                        --cuda-version ${{ inputs.cuda-version }} \
                        --ubuntu-version ${{ inputs.ubuntu-version }} \
                        --build-and-test python
        echo "::endgroup::"
    - name: Run Compute Sanitizer
      shell: bash
      run: |
        echo "::group::Run Compute Sanitizer"
        ci/premerge.py  --platform ${{ inputs.platform }} \
                        --cuda-version ${{ inputs.cuda-version }} \
                        --ubuntu-version ${{ inputs.ubuntu-version }} \
                        --build-and-test compute-sanitizer
        echo "::endgroup::"
    - name: Run Large Dataset Stability test
      shell: bash
      run: |
        echo "::group::Run Large Dataset Stability test"
        ci/premerge.py  --platform ${{ inputs.platform }} \
                        --cuda-version ${{ inputs.cuda-version }} \
                        --ubuntu-version ${{ inputs.ubuntu-version }} \
                        --build-and-test stability
        echo "::endgroup::"
