name: GitHub Pages
on:
  push:
    branches: ["public"]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: write
  pull-requests: write
  checks: write
  issues: read
jobs:
  deploy_docs:
    name: Deploy the docs
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0
          fetch-tags: true
      - name: Install doxygen
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends doxygen
      - name: Build docs
        run: |
          cd docs
          pip3 install -r requirements.txt
          make SPHINXOPTS=-W multi-docs
          touch ./_build/.nojekyll
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build
