name: nvblox premerge
on:
  pull_request:
jobs:
  premerge_x86_cu11_u22:
    name: premerge_x86_cu11_u22
    runs-on: [self-hosted, gpu] # GPU jobs will run on AWS
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: premerge_x86_cu11_u22 - Unit tests
        uses: ./.github/actions/build-and-test
        with:
          platform: x86_64
          cuda-version: '11'
          ubuntu-version: '22'
          ngc-api-key: ${{ secrets.NGC_API_KEY }}

# premerge_x86_cu12_u22:
# premerge_x86_cu13_u24:
